import assert from "node:assert/strict";
const base=process.env.TEST_BASE_URL||"http://localhost:5173";
const origin=new URL(base).origin;
if(!["localhost","127.0.0.1"].includes(new URL(base).hostname))throw new Error("Smoke test only runs against a local development server.");
let r=await fetch(base+"/api/transcripts");assert.equal(r.status,401);
const signin=await fetch(base+"/signin-with-chatgpt?return_to=/",{redirect:"manual"});
const cookie=signin.headers.get("set-cookie")?.split(";")[0];assert.ok(cookie);
const headers={cookie,origin,"content-type":"application/json"};
r=await fetch(base+"/api/transcripts",{headers:{cookie}});assert.equal(r.status,200);
assert.ok(Array.isArray((await r.json()).transcripts));
r=await fetch(base+"/api/transcripts",{method:"POST",headers,body:JSON.stringify({title:"Old demo",text:"ሰላም",language:"ti",sampleId:"sample-ti"})});assert.equal(r.status,405);
r=await fetch(base+"/api/transcripts/00000000-0000-4000-8000-000000000000",{headers:{cookie}});assert.equal(r.status,404);
r=await fetch(base+"/api/transcribe",{method:"POST",headers});assert.equal(r.status,503);
console.log("PASS: authenticated library, removed demo creation, unknown transcript, and missing speech-engine guard.");
